# Generated by Django 3.2 on 2021-06-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_appointment', '0002_auto_20210601_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='book',
            name='time',
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
