# Generated by Django 3.2 on 2021-07-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_appointment', '0003_auto_20210608_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passport',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(),
        ),
    ]
