# Generated by Django 3.2 on 2021-07-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_appointment', '0004_auto_20210702_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
