# Generated by Django 3.2 on 2021-08-09 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_appointment', '0006_auto_20210806_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book_appointment.profile'),
        ),
    ]
