# Generated by Django 3.2 on 2021-09-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_appointment', '0010_venue_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='person',
        ),
    ]
