# Generated by Django 3.2 on 2021-09-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_appointment', '0013_alter_venue_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='user',
            new_name='person',
        ),
    ]
