# Generated by Django 3.2 on 2021-09-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_appointment', '0014_rename_user_venue_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='hospital',
            field=models.CharField(choices=[('KNH', 'Kenyatta hsp'), ('MGT', 'Mbagathi hsp'), ('PMW', 'Pumwani hsp'), ('NRB', 'Nairobi hsp'), ('KKG', 'Kakamega hsp')], default='NRB', max_length=30),
        ),
    ]
